### ISSUE TITLE
Implement an after hours workflow

### ISSUE THREAD

**Issue by sclark-rvtd** [RVTD/RideTeam#122]
Right now all after hours NEMT is not handled in OBSS.  This is an epic issue to allow the after hours call takers to determine a member's eligibility, then assign a provider.  The provider needs to be able to pick up a ride form and fill out the necessary information.

Step:
- [x] 1.  Determine the workflow (Discussed and implementing, may need documentation)
- [x] 2.  Put together a user interface for the provider to see their rides. #123
- [x] 3.  Complete a user interface for the after hours call taker #132
- [x] 4.  Complete a user interface for the provider to submit a ride. #144

**Comment by sclark-rvtd** [comment]
Right now the after hours call takers have access to Oregon's medicaid database.  They can look up a member by last name, first name and birthdate OR last name, first name and Prime.

**Comment by sclark-rvtd** [comment]
This has been completed.  If we find problems, we will open new issues.
